<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Albeoris.Games.FF8.Jsm\Albeoris.Games.FF8.Jsm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.jsm" />
  </ItemGroup>

</Project>
