<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="010 Editor\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Albeoris.Games.Core\Albeoris.Games.Core\Albeoris.Games.Core.csproj" />
      <ProjectReference Include="..\Albeoris.Games.FF8.FlArchives.Abstractions\Albeoris.Games.FF8.FlArchives.Abstractions.csproj" />
    </ItemGroup>

</Project>
