<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Albeoris.Games.Core\Albeoris.Games.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="NsResources\Resources\*.txt" />
    </ItemGroup>

</Project>
