<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Albeoris.Games.FF8.TextEncoding\Albeoris.Games.FF8.TextEncoding.csproj" />
    <ProjectReference Include="..\Albeoris.Games.FF8.MngrpBin.Abstractions\Albeoris.Games.FF8.MngrpBin.Abstractions.csproj" />
    <ProjectReference Include="..\Albeoris.Games.FF8.MngrpBin\Albeoris.Games.FF8.MngrpBin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.zip" />
  </ItemGroup>

</Project>
