<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Albeoris.Games.Core.Abstractions\Albeoris.Games.Core.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' != 'net8.0'">
      <Compile Remove="NsCollections\OrderedDictionary.cs" />
    </ItemGroup>

</Project>
