<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Albeoris.Games.FF8.KernelBin.Abstractions\Albeoris.Games.FF8.KernelBin.Abstractions.csproj" />
      <ProjectReference Include="..\Albeoris.Games.FF8.KernelBin\Albeoris.Games.FF8.KernelBin.csproj" />
    </ItemGroup>

</Project>
