<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Albeoris.Games.Core\Albeoris.Games.Core\Albeoris.Games.Core.csproj" />
        <ProjectReference Include="..\Albeoris.Games.FF8.Encoding.Abstractions\Albeoris.Games.FF8.Encoding.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\*.json" />
    </ItemGroup>

</Project>
