<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Albeoris.Games.FF8.TextEncoding\Albeoris.Games.FF8.TextEncoding.csproj" />
        <ProjectReference Include="..\Albeoris.Games.FF8.KernelBin.Abstractions\Albeoris.Games.FF8.KernelBin.Abstractions.csproj" />
        <InternalsVisibleTo Include="Albeoris.Games.FF8.KernelBin.Tests" />
    </ItemGroup>

</Project>
