<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Albeoris.Games.FF8.Msd\Albeoris.Games.FF8.Msd.csproj" />
    <ProjectReference Include="..\Albeoris.Games.FF8.TextEncoding\Albeoris.Games.FF8.TextEncoding.csproj" />
  </ItemGroup>

</Project>
