<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ValveKeyValue" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Albeoris.Games.SteamLibrary.Abstractions\Albeoris.Games.SteamLibrary.Abstractions.csproj" />
  </ItemGroup>

</Project>
